name: API Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: 'x64'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Tests
      run: mvn test

    - name: Archive Extent Report
      uses: actions/upload-artifact@v2
      with:
        name: extent-report
        path: extent-reports.html
